# =============================================
# Service cho Kafka
# =============================================
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: thingsboard
spec:
  selector:
    app: kafka
  ports:
    - name: broker
      port: 9092
      targetPort: 9092

---
# =============================================
# Deployment cho Kafka (bitnami/kafka:3.2.0)
# =============================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: thingsboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:3.2.0
          ports:
            - containerPort: 9092
          env:
            # Cho phép kết nối PLAINTEXT (cho dev/test)
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            # Chỉ định địa chỉ Zookeeper
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            # Lắng nghe & Advertise cho client
            - name: KAFKA_CFG_LISTENERS
              value: "PLAINTEXT://:9092"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka:9092"
            # Định danh broker
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: ZOO_ADMINSERVER_ENABLED
              value: "false"