# =============================================
# Service cho Tb-core
# =============================================
apiVersion: v1
kind: Service
metadata:
  name: tb-core
  namespace: thingsboard
spec:
  selector:
    app: tb-core
  ports:
    - name: tb-core
      port: 8080
      targetPort: 8080

---
# =============================================
# Deployment cho Tb-core (docker.io/thingsboard/tb-node:3.6.0)
# =============================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tb-core
  namespace: thingsboard
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: tb-core
  template:
    metadata:
      labels:
        app: tb-core
    spec:
      containers:
        - name: tb-core
          image: docker.io/thingsboard/tb-node:3.6.0
          ports:
            - containerPort: 8080
            - containerPort: 7070
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
            limits:
              cpu: "4"
              memory: "6Gi"
          volumeMounts:
            - name: tb-conf-volume
              mountPath: /config
          env:
            - name: TB_SERVICE_TYPE
              value: "tb-core"
            - name: EDGES_ENABLED
              value: "true"
            - name: JS_EVALUATOR
              value: "remote"
            - name: TRANSPORT_TYPE
              value: "remote"
            - name: HTTP_LOG_CONTROLLER_ERROR_STACK_TRACE
              value: "false"
            - name: METRICS_ENABLED
              value: "true"
            - name: METRICS_ENDPOINTS_EXPOSE
              value: "prometheus"
          envFrom:
            - configMapRef:
                name: tb-redis-configmap
            - configMapRef:
                name: tb-kafka-configmap
            - configMapRef:
                name: tb-database-configmap
            - configMapRef:
                name: tb-zookeeper-configmap
      volumes:
        - name: tb-conf-volume
          configMap:
            name: tb-core-configmap
            items:
              - key: "logback.xml"
                path: "logback.xml"
              - key: "thingsboard.conf"
                path: "thingsboard.conf"
