apiVersion: apps/v1
kind: Deployment
metadata:
  name: tb-js-executor
  namespace: thingsboard
spec:
  replicas: 10
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: tb-js-executor
  template:
    metadata:
      labels:
        app: tb-js-executor
    spec:
      containers:
        - name: tb-js-executor
          image: docker.io/thingsboard/tb-js-executor:3.6.0
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "1"
              memory: "150Mi"
          env:
            - name: REMOTE_JS_EVAL_REQUEST_TOPIC
              value: "js_eval.requests"
            - name: LOGGER_LEVEL
              value: "info"
            - name: LOG_FOLDER
              value: "logs"
            - name: LOGGER_FILENAME
              value: "tb-js-executor-%DATE%.log"
            - name: DOCKER_MODE
              value: "true"
            - name: SCRIPT_BODY_TRACE_FREQUENCY
              value: "1000"
            - name: NODE_OPTIONS
              value: "--max-old-space-size=200"
            #QUEUE
            - name: TB_QUEUE_TYPE
              value: "kafka"
            - name: TB_KAFKA_SERVERS
              value: "kafka:9092"