apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tb-rule-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tb-rule-engine  # Tên Deployment bạn muốn auto-scale
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        # Theo dõi CPU usage
        name: cpu
        target:
          # Chọn kiểu đo: Utilization = so sánh (usage / requests) * 100%
          type: Utilization
          averageUtilization: 80  # Nếu vượt quá 80% CPU request sẽ scale up
    - type: Resource
      resource:
        # Theo dõi Memory usage
        name: memory
        target:
          type: Utilization
          averageUtilization: 70  # Nếu vượt 70% memory request sẽ scale up
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Pods         # Tăng theo số pod
          value: 1           # Chỉ tăng 1 pod
          periodSeconds: 30  # Mỗi 30s mới được tăng tiếp
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods         # Giảm theo số pod
          value: 1           # Chỉ giảm 1 pod
          periodSeconds: 60  # Mỗi 60s mới giảm tiếp
